[versions]
cxf = "4.2.0"
slf4j = "2.0.17"
junit = "6.0.2"

[libraries]
junit-Bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platformReporting = { module = "org.junit.platform:junit-platform-reporting" }
assertj-core = { module = "org.assertj:assertj-core", version = "3.27.7" }
javapoet = { module = "com.palantir.javapoet:javapoet", version = "0.11.0" }
gradle-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "8.2.1" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" } # Unused; exists to allow automatic updates.
cxf-toolsWsdltoCore = { module = "org.apache.cxf:cxf-tools-wsdlto-core", version.ref = "cxf" }
cxf-toolsWsdltoFrontendJs = { module = "org.apache.cxf:cxf-tools-wsdlto-frontend-javascript", version.ref = "cxf" }


[plugins]
gitPublish = { id = "org.ajoberstar.git-publish", version = "5.1.3" }
asciidoctorJvmConvert = { id = "org.asciidoctor.jvm.convert", version = "4.0.5" }
spotless = { id = "com.diffplug.spotless" }
jreleaser = { id = "org.jreleaser", version = "1.22.0" }
